version: 1.0.{build}
skip_tags: true
shallow_clone: true
build: off
deploy: off

skip_commits:
  # Skip stable release commits
  message: /^ *v? *\d+\.\d+\.\d+ *$/

environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "4"
    - nodejs_version: "5"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - cinst Firefox -y
  - cinst GoogleChrome -y
  - cinst Opera -y
  - npm i

test_script:
  - set DEBUG=win-detect-browsers
  - node test.js --no-operaversions
